package org.climbing.domain;
// Generated 14-feb-2016 21.19.01 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Category generated by hbm2java
 */
@Entity
//@Table(name = "category", catalog = "3dc")
@Table(name = "category")
public class Category implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Date creationDate;
	private List<Comment> comments = new ArrayList<Comment>();

	public Category() {
	}

	public Category(int id) {
		this.id = id;
	}

//	public Category(int id, String name, String description, Date creationDate, Set comments) {
//		this.id = id;
//		this.name = name;
//		this.description = description;
//		this.creationDate = creationDate;
//		this.comments = comments;
//	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	
	
//	public Set getComments() {
//		return this.comments;
//	}
//
//	public void setComments(Set comments) {
//		this.comments = comments;
//	}

}
