package org.climbing.domain;
// Generated 14-feb-2016 21.19.01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "configurations")
public class Configurations implements java.io.Serializable {

	private String key;
	private String value;

	public Configurations() {
	}

	@Id
	@Column(name = "key", unique = true, nullable = false)
	public String getKey() {
		return key;
	}
	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value")
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
}
